blank_issues_enabled: false
contact_links:
  - name: Community Questions & Discussions
    url: https://github.com/WhiteRoseLK/neossh/issues
    about: Ask questions, get help, or discuss ideas with the community.